name: debug
on: push
  
jobs:
  platforms:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - lambda
          - codesandbox

    steps:
      - if: matrix.platform == 'codesandbox'
        run: echo "Execution conditional!"

      - run: echo "Execute always!"
